[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    " <TAB>: Completion
    inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ deoplete#manual_complete()
    function! s:check_back_space() abort
        let col = col('.') - 1
        return !col || getline('.')[col - 1]  =~ '\s'
    endfunction

    " <S-TAB>: Completion back
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
        \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

    " Enable at start-up
    call deoplete#enable()
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
    " Plugin key-mappings.
    imap <C-f> <Plug>(neosnippet_expand_or_jump)
    smap <C-f> <Plug>(neosnippet_expand_or_jump)
    xmap <C-f> <Plug>(neosnippet_expand_target)

    " Personal snippets directory
    let g:neosnippet#snippets_directory = '~/.config/nvim/snippets'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_no_default_key_mappings = 1
    nnoremap <Space>r :<C-u>QuickRun<CR>
    nnoremap <Space>q <C-w>w:q<CR>
'''

hook_source = '''
    let g:quickrun_config = {
    \    "_" : {
    \        'outputter/error/success' : 'buffer',
    \        'outputter/error/error' : 'quickfix',
    \        'outputter/quickfix/open_cmd' : 'copen',
    \        'outputter/buffer/close_on_empty' : '1',
    \        'outputter/buffer/split' : ':bo 16sp',
    \        'runner' : 'vimproc',
    \        'runner/vimproc/updatetime' : 50,
    \        'hook/time/enable' : 1
    \    }
    \}
'''
